const SUPABASE_URL='https://ogkhaomdfrmyqxmhutkd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_UlT0jgbh9PtA4wLfRN1yWA_t4yngpmk';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const state={tab:'dashboard',month:new Date().toISOString().slice(0,7),employees:[],products:[],targets:[],tasks:[],sales:[],revenue:[],user:null};

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const monthStart=m=>m+'-01';
const monthEnd=m=>{const [y,mo]=m.split('-').map(Number);return new Date(y,mo,0).toISOString().slice(0,10)};
const inMonth=(d,m)=>String(d||'').slice(0,7)===m;
const empName=id=>state.employees.find(x=>x.id===id)?.full_name||'Unknown';
const prodName=id=>state.products.find(x=>x.id===id)?.name||'Unassigned';
const notify=(msg,bad=false)=>{const n=document.getElementById('toast');if(!n)return;n.textContent=msg;n.className='fixed right-5 bottom-5 z-50 px-5 py-3 rounded-2xl shadow-lg text-sm '+(bad?'bg-red-700 text-white':'bg-[#1C301F] text-white');setTimeout(()=>n.className='hidden',2800)};
async function q(p){const r=await p;if(r.error)throw r.error;return r.data||[]}

async function loadAll(){
 const [employees,products,targets,tasks,sales,revenue]=await Promise.all([
  q(db.from('employees').select('*').order('full_name')),
  q(db.from('products_services').select('*').order('name')),
  q(db.from('monthly_targets').select('*')),
  q(db.from('employee_tasks').select('*').order('due_date',{ascending:true})),
  q(db.from('sales').select('*').order('sale_date',{ascending:false})),
  q(db.from('revenue_entries').select('*').order('entry_date',{ascending:false}))
 ]);
 Object.assign(state,{employees,products,targets,tasks,sales,revenue});
 render();
}

function shell(){
 return '<div class="min-h-screen bg-[#F7F6F2] text-[#1C301F]"><header class="sticky top-0 z-40 bg-white/95 backdrop-blur border-b border-[#1C301F]/10"><div class="max-w-[1500px] mx-auto px-5 py-4 flex items-center justify-between gap-4"><div><div class="text-[11px] uppercase tracking-[.22em] text-[#657253]">Private Administration</div><h1 class="text-xl md:text-2xl font-black">ATSFY Employee Revenue OS</h1></div><div class="flex items-center gap-2"><span class="hidden md:block text-xs text-gray-500">'+esc(state.user?.email)+'</span><button onclick="logout()" class="px-4 py-2 rounded-xl border bg-white hover:bg-gray-50">Sign out</button></div></div></header><div class="max-w-[1500px] mx-auto p-4 md:p-6"><div class="flex flex-col lg:flex-row gap-4"><aside class="lg:w-56 shrink-0"><nav class="bg-white rounded-2xl border p-2 space-y-1">'+nav('dashboard','Dashboard')+nav('employees','Employees')+nav('products','Products & Services')+nav('targets','Monthly Targets')+nav('tasks','Tasks')+nav('sales','Sales')+nav('revenue','Revenue')+nav('reports','Reports')+'</nav></aside><main class="flex-1 min-w-0">'+pageTitle()+'<div id="content"></div></main></div></div><div id="toast" class="hidden"></div></div>';
}
function nav(id,label){return '<button onclick="setTab(\''+id+'\')" class="w-full text-left px-4 py-3 rounded-xl text-sm font-semibold '+(state.tab===id?'bg-[#1C301F] text-white':'hover:bg-[#F7F6F2]')+'">'+label+'</button>'}
function pageTitle(){const labels={dashboard:'Dashboard',employees:'Employees',products:'Products & Services',targets:'Monthly Targets',tasks:'Tasks',sales:'Sales',revenue:'Revenue Entries',reports:'Reports'};return '<div class="mb-5"><h2 class="text-2xl font-black">'+labels[state.tab]+'</h2><p class="text-sm text-gray-500 mt-1">Admin-only operating data. Access is enforced by Supabase Auth + RLS.</p></div>'}
function monthControl(){return '<div class="flex items-center gap-2"><label class="text-xs font-semibold text-gray-500">Month</label><input id="monthPicker" type="month" value="'+state.month+'" onchange="changeMonth(this.value)" class="border rounded-xl px-3 py-2 bg-white"></div>'}
function selectHtml(id,items,placeholder,selected='',extra=''){return '<select id="'+id+'" '+extra+' class="w-full border rounded-xl px-3 py-2 bg-white"><option value="">'+placeholder+'</option>'+items.map(x=>'<option value="'+x.id+'" '+(x.id===selected?'selected':'')+'>'+esc(x.label)+'</option>').join('')+'</select>'}
function productOptions(selected=''){return selectHtml('product',state.products.map(x=>({id:x.id,label:x.name+' · '+x.type})), 'Select product/service',selected)}
function employeeOptions(selected=''){return selectHtml('employee',state.employees.map(x=>({id:x.id,label:x.full_name+(x.status!=='active'?' · '+x.status:'')})),'Select employee',selected)}
function card(label,value,sub=''){return '<div class="bg-white rounded-2xl border p-5"><div class="text-xs uppercase tracking-wider text-gray-500">'+label+'</div><div class="text-2xl font-black mt-2">'+value+'</div><div class="text-xs text-gray-500 mt-1">'+sub+'</div></div>'}

function render(){document.getElementById('app').innerHTML=shell();const c=document.getElementById('content');const views={dashboard:dashboardView,employees:employeesView,products:productsView,targets:targetsView,tasks:tasksView,sales:salesView,revenue:revenueView,reports:reportsView};c.innerHTML=views[state.tab]()}
function setTab(t){state.tab=t;render()}
function changeMonth(m){state.month=m;render()}

function dashboardView(){
 const s=state.sales.filter(x=>inMonth(x.sale_date,state.month)&&x.payment_status!=='cancelled');
 const r=state.revenue.filter(x=>inMonth(x.entry_date,state.month));
 const t=state.targets.filter(x=>x.month_start===monthStart(state.month));
 const tasks=state.tasks.filter(x=>inMonth(x.due_date,state.month));
 const completed=tasks.filter(x=>x.status==='completed').length;
 const target=t.reduce((a,x)=>a+Number(x.target_revenue||0),0), sales=s.reduce((a,x)=>a+Number(x.total_amount||0),0), rev=r.reduce((a,x)=>a+Number(x.amount||0),0);
 const achievement=target?((sales+rev)/target*100):0;
 const rows=state.employees.map(e=>{
   const et=t.filter(x=>x.employee_id===e.id).reduce((a,x)=>a+Number(x.target_revenue||0),0);
   const es=s.filter(x=>x.employee_id===e.id).reduce((a,x)=>a+Number(x.total_amount||0),0);
   const er=r.filter(x=>x.employee_id===e.id).reduce((a,x)=>a+Number(x.amount||0),0);
   const tc=tasks.filter(x=>x.employee_id===e.id&&x.status==='completed').length;
   return {e,et,es,er,tc};
 });
 return monthControl()+'<div class="grid sm:grid-cols-2 xl:grid-cols-5 gap-4 mt-4">'+card('Active employees',state.employees.filter(x=>x.status==='active').length,'Current roster')+card('Target revenue',money(target),state.month)+card('Recorded sales',money(sales),'Non-cancelled sales')+card('Other revenue',money(rev),'Revenue entries')+card('Achievement',achievement.toFixed(1)+'%','Tracked / target')+'</div><div class="bg-white border rounded-2xl mt-6 overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Employee performance · '+state.month+'</h3><p class="text-xs text-gray-500 mt-1">Tracked revenue = recorded sales + revenue entries.</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Employee</th><th class="p-3 text-right">Target</th><th class="p-3 text-right">Sales</th><th class="p-3 text-right">Other</th><th class="p-3 text-right">Tracked</th><th class="p-3 text-right">Achv.</th><th class="p-3 text-right">Tasks</th></tr></thead><tbody>'+rows.map(x=>'<tr class="border-t"><td class="p-3 font-semibold">'+esc(x.e.full_name)+'</td><td class="p-3 text-right">'+money(x.et)+'</td><td class="p-3 text-right">'+money(x.es)+'</td><td class="p-3 text-right">'+money(x.er)+'</td><td class="p-3 text-right font-semibold">'+money(x.es+x.er)+'</td><td class="p-3 text-right">'+(x.et?((x.es+x.er)/x.et*100).toFixed(1):'0')+'%</td><td class="p-3 text-right">'+x.tc+'</td></tr>').join('')+'</tbody></table></div></div><div class="bg-white border rounded-2xl mt-6 overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Product / service performance</h3></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Item</th><th class="p-3 text-left">Type</th><th class="p-3 text-right">Sales</th><th class="p-3 text-right">Other revenue</th><th class="p-3 text-right">Total tracked</th></tr></thead><tbody>'+state.products.map(p=>{const ps=s.filter(x=>x.product_service_id===p.id).reduce((a,x)=>a+Number(x.total_amount||0),0);const pr=r.filter(x=>x.product_service_id===p.id).reduce((a,x)=>a+Number(x.amount||0),0);return '<tr class="border-t"><td class="p-3 font-semibold">'+esc(p.name)+'</td><td class="p-3">'+esc(p.type)+'</td><td class="p-3 text-right">'+money(ps)+'</td><td class="p-3 text-right">'+money(pr)+'</td><td class="p-3 text-right font-semibold">'+money(ps+pr)+'</td></tr>'}).join('')+'</tbody></table></div></div>';
}

function employeesView(){
 return '<div class="grid xl:grid-cols-[380px_1fr] gap-5"><div class="bg-white border rounded-2xl p-5"><h3 class="font-bold mb-4">Add employee</h3><form onsubmit="addEmployee(event)" class="space-y-3"><input name="full_name" required placeholder="Full name" class="w-full border rounded-xl px-3 py-2"><input name="employee_code" placeholder="Employee code" class="w-full border rounded-xl px-3 py-2"><input name="email" type="email" placeholder="Email" class="w-full border rounded-xl px-3 py-2"><input name="phone" placeholder="Phone" class="w-full border rounded-xl px-3 py-2"><input name="designation" placeholder="Designation" class="w-full border rounded-xl px-3 py-2"><input name="department" placeholder="Department" class="w-full border rounded-xl px-3 py-2"><input name="joining_date" type="date" class="w-full border rounded-xl px-3 py-2"><select name="status" class="w-full border rounded-xl px-3 py-2"><option value="active">Active</option><option value="inactive">Inactive</option><option value="on_leave">On leave</option></select><textarea name="notes" placeholder="Notes" class="w-full border rounded-xl px-3 py-2"></textarea><button class="w-full bg-[#1C301F] text-white rounded-xl py-2.5 font-semibold">Add employee</button></form></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Employee roster · '+state.employees.length+'</h3></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Employee</th><th class="p-3 text-left">Code</th><th class="p-3 text-left">Role</th><th class="p-3 text-left">Status</th><th class="p-3 text-right">Action</th></tr></thead><tbody>'+state.employees.map(e=>'<tr class="border-t"><td class="p-3"><div class="font-semibold">'+esc(e.full_name)+'</div><div class="text-xs text-gray-500">'+esc(e.email)+'</div></td><td class="p-3">'+esc(e.employee_code)+'</td><td class="p-3">'+esc(e.designation||'')+'</td><td class="p-3">'+esc(e.status)+'</td><td class="p-3 text-right"><button onclick="deleteEmployee(\''+e.id+'\')" class="text-red-600 text-xs font-semibold">Delete</button></td></tr>').join('')+'</tbody></table></div></div></div>';
}
async function addEmployee(ev){ev.preventDefault();const f=new FormData(ev.target);try{await q(db.from('employees').insert(Object.fromEntries(f)));notify('Employee added');ev.target.reset();await loadAll()}catch(e){notify(e.message,true)}}
async function deleteEmployee(id){if(!confirm('Delete this employee? Related records may be blocked by foreign-key rules.'))return;try{await q(db.from('employees').delete().eq('id',id));notify('Employee deleted');await loadAll()}catch(e){notify(e.message,true)}}

function productsView(){
 return '<div class="grid xl:grid-cols-[380px_1fr] gap-5"><div class="space-y-4"><div class="bg-white border rounded-2xl p-5"><h3 class="font-bold mb-4">Add product / service</h3><form onsubmit="addProduct(event)" class="space-y-3"><input name="name" required placeholder="Name" class="w-full border rounded-xl px-3 py-2"><select name="category" class="w-full border rounded-xl px-3 py-2"><option value="">Category</option><option>AI SaaS</option><option>EdTech</option><option>HealthTech</option><option>AgriTech</option><option>Development</option><option>Marketing</option><option>Other</option></select><select name="type" class="w-full border rounded-xl px-3 py-2"><option value="product">Product</option><option value="service">Service</option></select><input name="default_price" type="number" min="0" step="0.01" placeholder="Default price" class="w-full border rounded-xl px-3 py-2"><textarea name="notes" placeholder="Notes" class="w-full border rounded-xl px-3 py-2"></textarea><button class="w-full bg-[#1C301F] text-white rounded-xl py-2.5 font-semibold">Add item</button></form></div><button onclick="seedCatalog()" class="w-full bg-[#D9A43B] text-[#1C301F] rounded-xl py-3 font-bold">Seed ATSFY starter catalog</button></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Catalog · '+state.products.length+'</h3></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Name</th><th class="p-3 text-left">Category</th><th class="p-3 text-left">Type</th><th class="p-3 text-right">Price</th><th class="p-3 text-right">Action</th></tr></thead><tbody>'+state.products.map(p=>'<tr class="border-t"><td class="p-3 font-semibold">'+esc(p.name)+'</td><td class="p-3">'+esc(p.category)+'</td><td class="p-3">'+esc(p.type)+'</td><td class="p-3 text-right">'+money(p.default_price)+'</td><td class="p-3 text-right"><button onclick="deleteProduct(\''+p.id+'\')" class="text-red-600 text-xs font-semibold">Delete</button></td></tr>').join('')+'</tbody></table></div></div></div>';
}
async function addProduct(ev){ev.preventDefault();const f=new FormData(ev.target);const d=Object.fromEntries(f);d.default_price=Number(d.default_price||0);try{await q(db.from('products_services').insert(d));notify('Catalog item added');ev.target.reset();await loadAll()}catch(e){notify(e.message,true)}}
async function deleteProduct(id){if(!confirm('Delete this product/service?'))return;try{await q(db.from('products_services').delete().eq('id',id));notify('Item deleted');await loadAll()}catch(e){notify(e.message,true)}}
async function seedCatalog(){const names=[['GYMOS','AI SaaS','product'],['SavorOS','AI SaaS','product'],['EasyReport','AI SaaS','product'],['Clinova','HealthTech','product'],['ATSFY Hotel Management PMS','AI SaaS','product'],['ORDERHUB','AI SaaS','product'],['ATSFY Student ERP','EdTech','product'],['ATSFY Core Career Intelligence','CareerTech','product'],['ATSFYLearn','EdTech','product'],['Green-to-Gold','AgriTech','product'],['Kisan Mitra','AgriTech','product'],['Custom Website Development','Development','service'],['Digital Marketing & SEO','Marketing','service'],['AI Automation Services','AI Services','service']];try{await q(db.from('products_services').upsert(names.map(x=>({name:x[0],category:x[1],type:x[2]})),{onConflict:'name'}));notify('Starter catalog synced');await loadAll()}catch(e){notify(e.message,true)}}

function targetsView(){
 return '<div class="grid xl:grid-cols-[400px_1fr] gap-5"><div class="bg-white border rounded-2xl p-5"><div class="flex justify-between items-center mb-4"><h3 class="font-bold">Set monthly target</h3>'+monthControl()+'</div><form onsubmit="saveTarget(event)" class="space-y-3">'+employeeOptions()+'<div id="targetProduct">'+productOptions()+'</div><input name="target_units" type="number" min="0" step="1" placeholder="Target units" class="w-full border rounded-xl px-3 py-2"><input name="target_revenue" type="number" min="0" step="0.01" placeholder="Target revenue ₹" class="w-full border rounded-xl px-3 py-2"><textarea name="notes" placeholder="Notes" class="w-full border rounded-xl px-3 py-2"></textarea><button class="w-full bg-[#1C301F] text-white rounded-xl py-2.5 font-semibold">Save / update target</button></form></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Targets · '+state.month+'</h3></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Employee</th><th class="p-3 text-left">Product / Service</th><th class="p-3 text-right">Units</th><th class="p-3 text-right">Revenue target</th><th class="p-3 text-right">Action</th></tr></thead><tbody>'+state.targets.filter(x=>x.month_start===monthStart(state.month)).map(t=>'<tr class="border-t"><td class="p-3">'+esc(empName(t.employee_id))+'</td><td class="p-3">'+esc(prodName(t.product_service_id))+'</td><td class="p-3 text-right">'+Number(t.target_units||0)+'</td><td class="p-3 text-right">'+money(t.target_revenue)+'</td><td class="p-3 text-right"><button onclick="deleteTarget(\''+t.id+'\')" class="text-red-600 text-xs font-semibold">Delete</button></td></tr>').join('')+'</tbody></table></div></div></div>';
}
async function saveTarget(ev){ev.preventDefault();const f=new FormData(ev.target);const d=Object.fromEntries(f);d.employee_id=ev.target.querySelector('#employee')?.value;d.product_service_id=ev.target.querySelector('#product')?.value;d.month_start=monthStart(state.month);d.target_units=Number(d.target_units||0);d.target_revenue=Number(d.target_revenue||0);try{await q(db.from('monthly_targets').upsert(d,{onConflict:'employee_id,product_service_id,month_start'}));notify('Target saved');ev.target.reset();await loadAll()}catch(e){notify(e.message,true)}}
async function deleteTarget(id){try{await q(db.from('monthly_targets').delete().eq('id',id));notify('Target deleted');await loadAll()}catch(e){notify(e.message,true)}}

function tasksView(){
 return '<div class="grid xl:grid-cols-[420px_1fr] gap-5"><div class="bg-white border rounded-2xl p-5"><h3 class="font-bold mb-4">Create task</h3><form onsubmit="addTask(event)" class="space-y-3">'+employeeOptions()+'<div>'+productOptions()+'</div><input name="title" required placeholder="Task title" class="w-full border rounded-xl px-3 py-2"><textarea name="description" placeholder="Description" class="w-full border rounded-xl px-3 py-2"></textarea><input name="due_date" type="date" class="w-full border rounded-xl px-3 py-2"><select name="priority" class="w-full border rounded-xl px-3 py-2"><option value="medium">Medium priority</option><option value="high">High priority</option><option value="low">Low priority</option></select><button class="w-full bg-[#1C301F] text-white rounded-xl py-2.5 font-semibold">Create task</button></form></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Task tracker</h3></div><div class="divide-y">'+state.tasks.map(t=>'<div class="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div class="font-semibold">'+esc(t.title)+'</div><div class="text-xs text-gray-500">'+esc(empName(t.employee_id))+' · '+esc(prodName(t.product_service_id))+' · due '+esc(t.due_date||'—')+'</div></div><div class="flex items-center gap-2"><select onchange="updateTask(\''+t.id+'\',this.value)" class="border rounded-lg px-2 py-1 text-xs"><option '+(t.status==='pending'?'selected':'')+' value="pending">Pending</option><option '+(t.status==='in_progress'?'selected':'')+' value="in_progress">In progress</option><option '+(t.status==='completed'?'selected':'')+' value="completed">Completed</option><option '+(t.status==='cancelled'?'selected':'')+' value="cancelled">Cancelled</option></select><button onclick="deleteTask(\''+t.id+'\')" class="text-red-600 text-xs">Delete</button></div></div>').join('')+'</div></div></div>';
}
async function addTask(ev){ev.preventDefault();const f=new FormData(ev.target);const d=Object.fromEntries(f);d.employee_id=ev.target.querySelector('#employee')?.value;d.product_service_id=ev.target.querySelector('#product')?.value||null;d.status='pending';try{await q(db.from('employee_tasks').insert(d));notify('Task created');ev.target.reset();await loadAll()}catch(e){notify(e.message,true)}}
async function updateTask(id,status){try{await q(db.from('employee_tasks').update({status,completed_at:status==='completed'?new Date().toISOString():null}).eq('id',id));notify('Task updated');await loadAll()}catch(e){notify(e.message,true)}}
async function deleteTask(id){try{await q(db.from('employee_tasks').delete().eq('id',id));notify('Task deleted');await loadAll()}catch(e){notify(e.message,true)}}

function salesView(){
 return '<div class="grid xl:grid-cols-[420px_1fr] gap-5"><div class="bg-white border rounded-2xl p-5"><h3 class="font-bold mb-4">Record sale</h3><form onsubmit="addSale(event)" class="space-y-3">'+employeeOptions()+'<div>'+productOptions()+'</div><input name="sale_date" type="date" value="'+new Date().toISOString().slice(0,10)+'" required class="w-full border rounded-xl px-3 py-2"><input name="customer_name" placeholder="Customer / client" class="w-full border rounded-xl px-3 py-2"><input name="quantity" type="number" min="1" step="1" value="1" placeholder="Quantity" class="w-full border rounded-xl px-3 py-2"><input name="unit_price" type="number" min="0" step="0.01" required placeholder="Unit price ₹" class="w-full border rounded-xl px-3 py-2"><select name="payment_status" class="w-full border rounded-xl px-3 py-2"><option value="paid">Paid</option><option value="pending">Pending</option><option value="partial">Partial</option><option value="cancelled">Cancelled</option></select><textarea name="notes" placeholder="Notes" class="w-full border rounded-xl px-3 py-2"></textarea><button class="w-full bg-[#1C301F] text-white rounded-xl py-2.5 font-semibold">Record sale</button></form></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Sales ledger</h3></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Date</th><th class="p-3 text-left">Employee</th><th class="p-3 text-left">Item</th><th class="p-3 text-left">Customer</th><th class="p-3 text-right">Qty</th><th class="p-3 text-right">Amount</th><th class="p-3 text-left">Payment</th><th class="p-3"></th></tr></thead><tbody>'+state.sales.map(s=>'<tr class="border-t"><td class="p-3">'+esc(s.sale_date)+'</td><td class="p-3">'+esc(empName(s.employee_id))+'</td><td class="p-3">'+esc(prodName(s.product_service_id))+'</td><td class="p-3">'+esc(s.customer_name)+'</td><td class="p-3 text-right">'+s.quantity+'</td><td class="p-3 text-right">'+money(s.total_amount)+'</td><td class="p-3">'+esc(s.payment_status)+'</td><td class="p-3 text-right"><button onclick="deleteSale(\''+s.id+'\')" class="text-red-600 text-xs">Delete</button></td></tr>').join('')+'</tbody></table></div></div></div>';
}
async function addSale(ev){ev.preventDefault();const f=new FormData(ev.target);const d=Object.fromEntries(f);d.employee_id=ev.target.querySelector('#employee')?.value;d.product_service_id=ev.target.querySelector('#product')?.value;d.quantity=Number(d.quantity||1);d.unit_price=Number(d.unit_price||0);d.total_amount=d.quantity*d.unit_price;try{await q(db.from('sales').insert(d));notify('Sale recorded');ev.target.reset();await loadAll()}catch(e){notify(e.message,true)}}
async function deleteSale(id){try{await q(db.from('sales').delete().eq('id',id));notify('Sale deleted');await loadAll()}catch(e){notify(e.message,true)}}

function revenueView(){
 return '<div class="grid xl:grid-cols-[420px_1fr] gap-5"><div class="bg-white border rounded-2xl p-5"><h3 class="font-bold mb-4">Add revenue entry</h3><form onsubmit="addRevenue(event)" class="space-y-3">'+employeeOptions()+'<div>'+productOptions()+'</div><input name="entry_date" type="date" value="'+new Date().toISOString().slice(0,10)+'" required class="w-full border rounded-xl px-3 py-2"><input name="amount" type="number" min="0" step="0.01" required placeholder="Amount ₹" class="w-full border rounded-xl px-3 py-2"><input name="source" placeholder="Source (e.g. subscription, service)" class="w-full border rounded-xl px-3 py-2"><input name="reference_no" placeholder="Reference no." class="w-full border rounded-xl px-3 py-2"><textarea name="notes" placeholder="Notes" class="w-full border rounded-xl px-3 py-2"></textarea><button class="w-full bg-[#1C301F] text-white rounded-xl py-2.5 font-semibold">Add revenue</button></form></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Revenue entries</h3><p class="text-xs text-gray-500 mt-1">Use this for non-sale revenue or manually attributed revenue; avoid duplicating the same transaction in Sales.</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Date</th><th class="p-3 text-left">Employee</th><th class="p-3 text-left">Item</th><th class="p-3 text-left">Source</th><th class="p-3 text-right">Amount</th><th class="p-3"></th></tr></thead><tbody>'+state.revenue.map(r=>'<tr class="border-t"><td class="p-3">'+esc(r.entry_date)+'</td><td class="p-3">'+esc(empName(r.employee_id))+'</td><td class="p-3">'+esc(prodName(r.product_service_id))+'</td><td class="p-3">'+esc(r.source)+'</td><td class="p-3 text-right">'+money(r.amount)+'</td><td class="p-3 text-right"><button onclick="deleteRevenue(\''+r.id+'\')" class="text-red-600 text-xs">Delete</button></td></tr>').join('')+'</tbody></table></div></div></div>';
}
async function addRevenue(ev){ev.preventDefault();const f=new FormData(ev.target);const d=Object.fromEntries(f);d.employee_id=ev.target.querySelector('#employee')?.value;d.product_service_id=ev.target.querySelector('#product')?.value;d.amount=Number(d.amount||0);try{await q(db.from('revenue_entries').insert(d));notify('Revenue entry added');ev.target.reset();await loadAll()}catch(e){notify(e.message,true)}}
async function deleteRevenue(id){try{await q(db.from('revenue_entries').delete().eq('id',id));notify('Revenue deleted');await loadAll()}catch(e){notify(e.message,true)}}

function reportsView(){
 const rows=state.employees.map(e=>{const t=state.targets.filter(x=>x.month_start===monthStart(state.month)&&x.employee_id===e.id).reduce((a,x)=>a+Number(x.target_revenue||0),0);const s=state.sales.filter(x=>inMonth(x.sale_date,state.month)&&x.employee_id===e.id&&x.payment_status!=='cancelled').reduce((a,x)=>a+Number(x.total_amount||0),0);const r=state.revenue.filter(x=>inMonth(x.entry_date,state.month)&&x.employee_id===e.id).reduce((a,x)=>a+Number(x.amount||0),0);const tc=state.tasks.filter(x=>inMonth(x.due_date,state.month)&&x.employee_id===e.id&&x.status==='completed').length;return {e,t,s,r,tc,total:s+r,pct:t?(s+r)/t*100:0}});return '<div class="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-5"><div>'+monthControl()+'</div><button onclick="exportReport()" class="px-4 py-2.5 rounded-xl bg-[#1C301F] text-white font-semibold">Export CSV</button></div><div class="bg-white border rounded-2xl overflow-hidden"><div class="p-5 border-b"><h3 class="font-bold">Monthly employee report · '+state.month+'</h3></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Employee</th><th class="p-3 text-right">Target</th><th class="p-3 text-right">Sales</th><th class="p-3 text-right">Other</th><th class="p-3 text-right">Tracked</th><th class="p-3 text-right">Achievement</th><th class="p-3 text-right">Completed tasks</th></tr></thead><tbody>'+rows.map(x=>'<tr class="border-t"><td class="p-3 font-semibold">'+esc(x.e.full_name)+'</td><td class="p-3 text-right">'+money(x.t)+'</td><td class="p-3 text-right">'+money(x.s)+'</td><td class="p-3 text-right">'+money(x.r)+'</td><td class="p-3 text-right">'+money(x.total)+'</td><td class="p-3 text-right">'+x.pct.toFixed(1)+'%</td><td class="p-3 text-right">'+x.tc+'</td></tr>').join('')+'</tbody></table></div></div>';
}
function exportReport(){const rows=state.employees.map(e=>{const t=state.targets.filter(x=>x.month_start===monthStart(state.month)&&x.employee_id===e.id).reduce((a,x)=>a+Number(x.target_revenue||0),0);const s=state.sales.filter(x=>inMonth(x.sale_date,state.month)&&x.employee_id===e.id&&x.payment_status!=='cancelled').reduce((a,x)=>a+Number(x.total_amount||0),0);const r=state.revenue.filter(x=>inMonth(x.entry_date,state.month)&&x.employee_id===e.id).reduce((a,x)=>a+Number(x.amount||0),0);const tc=state.tasks.filter(x=>inMonth(x.due_date,state.month)&&x.employee_id===e.id&&x.status==='completed').length;return [e.full_name,e.email,state.month,t,s,r,s+r,t?((s+r)/t*100).toFixed(2):0,tc]});const csv=[['Employee','Email','Month','Target Revenue','Sales','Other Revenue','Tracked Revenue','Achievement %','Completed Tasks'],...rows].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='atsfy-employee-report-'+state.month+'.csv';a.click();URL.revokeObjectURL(a.href)}

async function logout(){await db.auth.signOut();location.reload()}
async function boot(){
 const {data:{user}}=await db.auth.getUser();
 if(!user){document.getElementById('login').classList.remove('hidden');return}
 if(user.app_metadata?.role!=='admin'){await db.auth.signOut();document.getElementById('login').classList.remove('hidden');document.getElementById('error').textContent='Access denied. Your account is authenticated but is not assigned the admin role.';return}
 state.user=user;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');await loadAll()
}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('email').value,password=document.getElementById('password').value;document.getElementById('error').textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email,password});if(error){document.getElementById('error').textContent=error.message;return}await boot()});
boot();
